apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 5
  strategy:
   type: RollingUpdate
   rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      name: proxy  
  template:
    metadata:
      labels:
        name: proxy
    spec:
      containers:
      - name: nginx
        image: kammana/nodeapp:v1
        resources:
          limits:
            memory: "500Mi"
            cpu: "1000m"
          requests: 
             memory: "128Mi"
             cpu: "500m"
        ports:
        - containerPort: 8080
       